### ISSUE TITLE
unable to compile with iron 0.6.0

### ISSUE THREAD

**Issue by anjumkaiser** [ubnt-intrepid/iron-slog#2]
Problem compiling, issue is because iron 0.6.0 is using different Request and Response structs.

```
error[E0277]: the trait bound `for<'r, 'r, 'r> router::Router: std::ops::Fn<(&'r mut iron::request::Request<'r, 'r>,)>` is not satisfied
  --> src/bin/store-backend\server\mod.rs:52:29
   |
52 |       let logger_middleware = LoggerMiddleware::new(
   |  _____________________________^
53 | |         router,
54 | |         logger.new(o!("child" => "routes")),
55 | |         logger_formatter,
56 | |     );
   | |_____^ the trait `for<'r, 'r, 'r> std::ops::Fn<(&'r mut iron::request::Request<'r, 'r>,)>` is not implemented for `router::Router`
   |
   = note: required because of the requirements on the impl of `iron::middleware::Handler` for `router::Router`
   = note: required by `iron_slog::LoggerMiddleware`
```

**Comment by bnewbold** [comment]
I ran in to the same issue. If this project (`iron-slog`) isn't being maintained, it would be nice to at least declare the dependencies as, eg, `iron = "~0.5"` instead of `iron = "^0.5"` to clarify that 0.6 won't work.

**Comment by ubnt-intrepid** [comment]
fixed in #3.
